// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi4jnY0fH8yPiDCEfO9u9kCabZt5XpYkY',
    appId: '1:1064776457869:web:07c43c2bc18a7dcf4c4cc4',
    messagingSenderId: '1064776457869',
    projectId: 'project-candil',
    authDomain: 'project-candil.firebaseapp.com',
    storageBucket: 'project-candil.firebasestorage.app',
    measurementId: 'G-D192K38BHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAwDIvBimU2SeoqzCDXzDIIWB7Fv_WDwo',
    appId: '1:1064776457869:android:1a95c19bc40c831c4c4cc4',
    messagingSenderId: '1064776457869',
    projectId: 'project-candil',
    storageBucket: 'project-candil.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNTiF83HS7gwJ705NhirmnklM4xN5hCFg',
    appId: '1:1064776457869:ios:0123719cd4b5b85a4c4cc4',
    messagingSenderId: '1064776457869',
    projectId: 'project-candil',
    storageBucket: 'project-candil.firebasestorage.app',
    iosBundleId: 'com.example.candil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNTiF83HS7gwJ705NhirmnklM4xN5hCFg',
    appId: '1:1064776457869:ios:0123719cd4b5b85a4c4cc4',
    messagingSenderId: '1064776457869',
    projectId: 'project-candil',
    storageBucket: 'project-candil.firebasestorage.app',
    iosBundleId: 'com.example.candil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi4jnY0fH8yPiDCEfO9u9kCabZt5XpYkY',
    appId: '1:1064776457869:web:b24b34e78d8bf0f14c4cc4',
    messagingSenderId: '1064776457869',
    projectId: 'project-candil',
    authDomain: 'project-candil.firebaseapp.com',
    storageBucket: 'project-candil.firebasestorage.app',
    measurementId: 'G-RRV07D404Y',
  );
}
